// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Branch is one parsed local branch.
 */
export interface Branch {
    "Name": string;
    "IsCurrent": boolean;
    "Upstream": string;
    "Ahead": number;
    "Behind": number;
    "LastHash": string;
    "LastSubject": string;
    "LastWhen": string;
}

/**
 * Commit is one parsed log entry.
 */
export interface Commit {
    "Hash": string;
    "Short": string;
    "Author": string;
    "Email": string;
    "When": string;
    "Subject": string;
}

/**
 * FileChange is one entry from git status.
 */
export interface FileChange {
    /**
     * human-readable index (staged) state
     */
    "Staged": string;

    /**
     * human-readable working-tree state
     */
    "Unstaged": string;
    "Path": string;

    /**
     * set for renames/copies
     */
    "OrigPath": string;
}

/**
 * Status is the parsed result of `git status --porcelain=v2 --branch`.
 */
export interface Status {
    "Branch": string;
    "Upstream": string;
    "Ahead": number;
    "Behind": number;
    "Detached": boolean;
    "Changes": FileChange[] | null;
    "Untracked": string[] | null;
}
