// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BlameLine is one line of a file with the commit that last touched it.
 */
export interface BlameLine {
    /**
     * 1-based line number in the current file
     */
    "Line": number;

    /**
     * short commit hash
     */
    "Short": string;

    /**
     * author name
     */
    "Author": string;

    /**
     * the line's text
     */
    "Content": string;
}

/**
 * Branch is one parsed local branch.
 */
export interface Branch {
    "Name": string;
    "IsCurrent": boolean;
    "Upstream": string;
    "Ahead": number;
    "Behind": number;
    "LastHash": string;
    "LastSubject": string;
    "LastWhen": string;
}

/**
 * Commit is one parsed log entry.
 */
export interface Commit {
    "Hash": string;
    "Short": string;
    "Author": string;
    "Email": string;
    "When": string;
    "Subject": string;
}

/**
 * CommitDetail is a single commit's metadata plus its file diffs.
 */
export interface CommitDetail {
    "Hash": string;
    "Short": string;
    "Author": string;
    "Email": string;
    "Date": string;
    "Subject": string;
    "Body": string;
    "Files": FileDiff[] | null;
}

/**
 * ConflictFile is a conflicted file's regions plus the raw marked-up content.
 */
export interface ConflictFile {
    "Path": string;
    "Hunks": ConflictHunk[] | null;
    "Raw": string;
}

/**
 * ConflictHunk is one conflict region: the "ours" and "theirs" content.
 */
export interface ConflictHunk {
    /**
     * stage 2 — current branch (HEAD)
     */
    "Ours": string[] | null;

    /**
     * stage 3 — the merged-in branch
     */
    "Theirs": string[] | null;
}

/**
 * FileChange is one entry from git status.
 */
export interface FileChange {
    /**
     * human-readable index (staged) state
     */
    "Staged": string;

    /**
     * human-readable working-tree state
     */
    "Unstaged": string;
    "Path": string;

    /**
     * set for renames/copies
     */
    "OrigPath": string;
}

/**
 * FileDiff is the diff for a single file.
 */
export interface FileDiff {
    "OldPath": string;
    "NewPath": string;
    "Binary": boolean;
    "Hunks": Hunk[] | null;
}

/**
 * Hunk is one @@ ... @@ block.
 */
export interface Hunk {
    "Header": string;
    "Lines": Line[] | null;
}

/**
 * Line is one line within a hunk.
 */
export interface Line {
    "Kind": LineKind;
    "Content": string;
    "OldNum": number;
    "NewNum": number;
}

/**
 * LineKind classifies a diff line.
 */
export enum LineKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    LineContext = "context",
    LineAdd = "add",
    LineRemove = "remove",
};

/**
 * ReflogEntry is one line of `git reflog` — where HEAD moved and why.
 */
export interface ReflogEntry {
    /**
     * abbreviated commit hash HEAD pointed at
     */
    "Short": string;

    /**
     * e.g. "HEAD@{0}"
     */
    "Selector": string;

    /**
     * commit, reset, checkout, merge, rebase, pull, ...
     */
    "Action": string;

    /**
     * the rest of the description
     */
    "Message": string;
}

/**
 * Stash is one entry from `git stash list`.
 */
export interface Stash {
    /**
     * e.g. "stash@{0}"
     */
    "Ref": string;

    /**
     * 0-based position
     */
    "Index": number;

    /**
     * branch the stash was made on (best-effort parse)
     */
    "Branch": string;

    /**
     * the stash description
     */
    "Message": string;
}

/**
 * Status is the parsed result of `git status --porcelain=v2 --branch`.
 */
export interface Status {
    "Branch": string;
    "Upstream": string;
    "Ahead": number;
    "Behind": number;
    "Detached": boolean;
    "Changes": FileChange[] | null;
    "Untracked": string[] | null;
}

/**
 * Tag is one entry from the tag list, with where it exists.
 */
export interface Tag {
    "Name": string;

    /**
     * annotation message or the tagged commit's subject (local only)
     */
    "Subject": string;

    /**
     * exists in the local repo
     */
    "Local": boolean;

    /**
     * exists on origin
     */
    "Remote": boolean;
}
