// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * GitService is the bound service the frontend calls. Every method here
 * delegates to the same internal/ engine the CLI uses.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as ghapi$0 from "../internal/ghapi/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as gitops$0 from "../internal/gitops/models.js";

export function AddLabels($number: number, labels: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(2840114755, $number, labels);
}

export function AddRemote(name: string, url: string): $CancellablePromise<void> {
    return $Call.ByID(2602220066, name, url);
}

export function Blame(path: string): $CancellablePromise<gitops$0.BlameLine[] | null> {
    return $Call.ByID(2208585044, path);
}

export function Branches(): $CancellablePromise<gitops$0.Branch[] | null> {
    return $Call.ByID(3913623929);
}

export function CancelRun(runID: number): $CancellablePromise<void> {
    return $Call.ByID(1044576492, runID);
}

export function CherryPick(rev: string): $CancellablePromise<void> {
    return $Call.ByID(4264862881, rev);
}

export function CherryPickAbort(): $CancellablePromise<void> {
    return $Call.ByID(4269242301);
}

export function CherryPickContinue(): $CancellablePromise<void> {
    return $Call.ByID(709290592);
}

/**
 * Clone clones url into dest and points the service at the new repo so the app
 * switches to it. Returns the cloned repo's path.
 */
export function Clone(url: string, dest: string): $CancellablePromise<string> {
    return $Call.ByID(3320935538, url, dest);
}

export function CommentPR($number: number, body: string): $CancellablePromise<string> {
    return $Call.ByID(1745206744, $number, body);
}

export function Commit(message: string): $CancellablePromise<string> {
    return $Call.ByID(471482348, message);
}

export function ConflictedFiles(): $CancellablePromise<string[] | null> {
    return $Call.ByID(4266596273);
}

export function CreateIssue(title: string, body: string): $CancellablePromise<string> {
    return $Call.ByID(4181657864, title, body);
}

export function CreateLabel(name: string, color: string, description: string): $CancellablePromise<void> {
    return $Call.ByID(1900097333, name, color, description);
}

export function CreatePR(title: string, body: string, head: string, base: string): $CancellablePromise<string> {
    return $Call.ByID(1421252495, title, body, head, base);
}

export function CreateRelease(tag: string, name: string, body: string, draft: boolean, prerelease: boolean): $CancellablePromise<ghapi$0.Release> {
    return $Call.ByID(166699366, tag, name, body, draft, prerelease);
}

export function CreateTag(name: string, message: string): $CancellablePromise<void> {
    return $Call.ByID(2405478571, name, message);
}

export function CurrentBranch(): $CancellablePromise<string> {
    return $Call.ByID(2226668274);
}

export function DefaultPRTitle(branch: string): $CancellablePromise<string> {
    return $Call.ByID(2798687038, branch);
}

export function DeleteAsset(assetID: number): $CancellablePromise<void> {
    return $Call.ByID(726459054, assetID);
}

export function DeleteBranch(name: string, force: boolean): $CancellablePromise<void> {
    return $Call.ByID(1821812546, name, force);
}

export function DeleteLabel(name: string): $CancellablePromise<void> {
    return $Call.ByID(1785281120, name);
}

export function DeleteRelease(id: number): $CancellablePromise<void> {
    return $Call.ByID(1545519419, id);
}

export function DeleteRemoteTag(name: string): $CancellablePromise<void> {
    return $Call.ByID(75779088, name);
}

export function DeleteTag(name: string): $CancellablePromise<void> {
    return $Call.ByID(436388354, name);
}

export function Diff(path: string, staged: boolean): $CancellablePromise<gitops$0.FileDiff[] | null> {
    return $Call.ByID(1934352874, path, staged);
}

export function DiscardPath(path: string): $CancellablePromise<void> {
    return $Call.ByID(2677726826, path);
}

/**
 * DownloadAsset returns the asset's contents base64-encoded so the frontend can
 * trigger a browser download.
 */
export function DownloadAsset(assetID: number): $CancellablePromise<string> {
    return $Call.ByID(820770519, assetID);
}

export function EditLabel(name: string, newName: string, color: string, description: string): $CancellablePromise<void> {
    return $Call.ByID(440390313, name, newName, color, description);
}

export function EditRelease(id: number, name: string, body: string, draft: boolean, prerelease: boolean): $CancellablePromise<ghapi$0.Release> {
    return $Call.ByID(3597022626, id, name, body, draft, prerelease);
}

export function Fetch(): $CancellablePromise<void> {
    return $Call.ByID(3105763379);
}

export function FetchTags(): $CancellablePromise<void> {
    return $Call.ByID(2222523430);
}

/**
 * GenerateReleaseNotes returns [name, body] so it binds cleanly to TS.
 */
export function GenerateReleaseNotes(tag: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(513076016, tag);
}

/**
 * GetRepoDir returns the current working directory.
 */
export function GetRepoDir(): $CancellablePromise<string> {
    return $Call.ByID(2807244446);
}

export function GetRun(runID: number): $CancellablePromise<ghapi$0.WorkflowRun> {
    return $Call.ByID(1972643456, runID);
}

export function Issues(state: string): $CancellablePromise<ghapi$0.Issue[] | null> {
    return $Call.ByID(1294470425, state);
}

export function JobLogs(jobID: number): $CancellablePromise<ghapi$0.JobLog> {
    return $Call.ByID(3461752551, jobID);
}

export function ListAssets(releaseID: number): $CancellablePromise<ghapi$0.Asset[] | null> {
    return $Call.ByID(1953238676, releaseID);
}

export function ListDispatchableWorkflows(): $CancellablePromise<ghapi$0.DispatchableWorkflow[] | null> {
    return $Call.ByID(1071859323);
}

export function ListIssueComments($number: number): $CancellablePromise<ghapi$0.IssueComment[] | null> {
    return $Call.ByID(4209960726, $number);
}

export function ListLabels(): $CancellablePromise<ghapi$0.Label[] | null> {
    return $Call.ByID(2781467806);
}

export function ListReleases(): $CancellablePromise<ghapi$0.Release[] | null> {
    return $Call.ByID(1457386739);
}

export function ListRemotes(): $CancellablePromise<gitops$0.Remote[] | null> {
    return $Call.ByID(2290322204);
}

export function ListRequestedReviewers($number: number): $CancellablePromise<ghapi$0.Reviewer[] | null> {
    return $Call.ByID(1061340549, $number);
}

export function ListReviewComments($number: number): $CancellablePromise<ghapi$0.ExistingComment[] | null> {
    return $Call.ByID(1633293631, $number);
}

export function ListReviews($number: number): $CancellablePromise<ghapi$0.Review[] | null> {
    return $Call.ByID(3728537402, $number);
}

export function ListRuns(limit: number): $CancellablePromise<ghapi$0.WorkflowRun[] | null> {
    return $Call.ByID(4052380023, limit);
}

export function ListTags(): $CancellablePromise<gitops$0.Tag[] | null> {
    return $Call.ByID(933116764);
}

export function Log(limit: number): $CancellablePromise<gitops$0.Commit[] | null> {
    return $Call.ByID(2074061505, limit);
}

export function LogRef(ref: string, limit: number): $CancellablePromise<gitops$0.Commit[] | null> {
    return $Call.ByID(2234953638, ref, limit);
}

export function MarkResolved(path: string): $CancellablePromise<void> {
    return $Call.ByID(2864979112, path);
}

export function Merge(branch: string): $CancellablePromise<void> {
    return $Call.ByID(4048865143, branch);
}

export function MergeAbort(): $CancellablePromise<void> {
    return $Call.ByID(3275036075);
}

export function MergeInProgress(): $CancellablePromise<boolean> {
    return $Call.ByID(296209399);
}

export function MergePR($number: number, method: string): $CancellablePromise<string> {
    return $Call.ByID(2365324437, $number, method);
}

export function PRChecks($number: number): $CancellablePromise<ghapi$0.CheckRun[] | null> {
    return $Call.ByID(3470830078, $number);
}

export function PRDetail($number: number): $CancellablePromise<ghapi$0.PRDetail | null> {
    return $Call.ByID(3903033078, $number);
}

export function PRDiff($number: number): $CancellablePromise<gitops$0.FileDiff[] | null> {
    return $Call.ByID(3658489820, $number);
}

export function PRTemplate(): $CancellablePromise<string> {
    return $Call.ByID(2667485909);
}

/**
 * PRs resolves owner/repo from the origin remote of the current dir.
 */
export function PRs(state: string): $CancellablePromise<ghapi$0.PR[] | null> {
    return $Call.ByID(3721264108, state);
}

export function Pull(rebase: boolean): $CancellablePromise<void> {
    return $Call.ByID(3924717390, rebase);
}

export function Push(setUpstream: boolean): $CancellablePromise<void> {
    return $Call.ByID(4024544461, setUpstream);
}

export function PushTag(name: string): $CancellablePromise<void> {
    return $Call.ByID(653298187, name);
}

export function ReadConflict(path: string): $CancellablePromise<gitops$0.ConflictFile | null> {
    return $Call.ByID(1015254207, path);
}

export function Rebase(base: string): $CancellablePromise<void> {
    return $Call.ByID(1192392517, base);
}

export function RebaseAbort(): $CancellablePromise<void> {
    return $Call.ByID(654207257);
}

export function RebaseContinue(): $CancellablePromise<void> {
    return $Call.ByID(1428905956);
}

export function RebaseInProgress(): $CancellablePromise<boolean> {
    return $Call.ByID(2123162065);
}

export function Reflog(limit: number): $CancellablePromise<gitops$0.ReflogEntry[] | null> {
    return $Call.ByID(1601046040, limit);
}

export function RemoveLabel($number: number, label: string): $CancellablePromise<void> {
    return $Call.ByID(540707925, $number, label);
}

export function RemoveRemote(name: string): $CancellablePromise<void> {
    return $Call.ByID(2331660635, name);
}

export function RemoveReviewer($number: number, login: string): $CancellablePromise<void> {
    return $Call.ByID(320614290, $number, login);
}

export function RenameBranch(oldName: string, newName: string): $CancellablePromise<void> {
    return $Call.ByID(1363441787, oldName, newName);
}

export function RenameRemote(oldName: string, newName: string): $CancellablePromise<void> {
    return $Call.ByID(424528649, oldName, newName);
}

export function ReplyToReviewComment($number: number, commentID: number, body: string): $CancellablePromise<void> {
    return $Call.ByID(2839797543, $number, commentID, body);
}

export function RequestReviewers($number: number, logins: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(4134688474, $number, logins);
}

export function RerunFailed(runID: number): $CancellablePromise<void> {
    return $Call.ByID(3190066500, runID);
}

export function RerunRun(runID: number): $CancellablePromise<void> {
    return $Call.ByID(651277306, runID);
}

export function Reset(rev: string, mode: string): $CancellablePromise<void> {
    return $Call.ByID(478003792, rev, mode);
}

export function ResolveOurs(path: string): $CancellablePromise<void> {
    return $Call.ByID(1197531072, path);
}

export function ResolveTheirs(path: string): $CancellablePromise<void> {
    return $Call.ByID(1737476826, path);
}

export function ResolveThread(threadID: string): $CancellablePromise<void> {
    return $Call.ByID(149470811, threadID);
}

export function Revert(rev: string): $CancellablePromise<void> {
    return $Call.ByID(2468644051, rev);
}

export function RevertAbort(): $CancellablePromise<void> {
    return $Call.ByID(2212313231);
}

export function RevertContinue(): $CancellablePromise<void> {
    return $Call.ByID(3855291498);
}

export function RunJobs(runID: number): $CancellablePromise<ghapi$0.Job[] | null> {
    return $Call.ByID(2818376490, runID);
}

export function SequencerInProgress(): $CancellablePromise<[boolean, boolean]> {
    return $Call.ByID(365654410);
}

export function SetIssueState($number: number, state: string): $CancellablePromise<void> {
    return $Call.ByID(3236175167, $number, state);
}

export function SetPRState($number: number, state: string): $CancellablePromise<void> {
    return $Call.ByID(972438818, $number, state);
}

/**
 * SetRepoDir lets the frontend re-point the service at another repo.
 */
export function SetRepoDir(dir: string): $CancellablePromise<void> {
    return $Call.ByID(1616087450, dir);
}

export function Show(rev: string): $CancellablePromise<gitops$0.CommitDetail | null> {
    return $Call.ByID(2821441612, rev);
}

export function SmartDeleteTag(name: string): $CancellablePromise<string> {
    return $Call.ByID(2023693563, name);
}

export function Stage(): $CancellablePromise<void> {
    return $Call.ByID(1407503261);
}

export function StagePath(path: string): $CancellablePromise<void> {
    return $Call.ByID(1959303550, path);
}

export function StashApply(ref: string): $CancellablePromise<void> {
    return $Call.ByID(3648520378, ref);
}

export function StashDrop(ref: string): $CancellablePromise<void> {
    return $Call.ByID(1123069703, ref);
}

export function StashList(): $CancellablePromise<gitops$0.Stash[] | null> {
    return $Call.ByID(615021102);
}

export function StashPop(ref: string): $CancellablePromise<void> {
    return $Call.ByID(106599041, ref);
}

export function StashSave(message: string, includeUntracked: boolean): $CancellablePromise<void> {
    return $Call.ByID(2954681087, message, includeUntracked);
}

export function Status(): $CancellablePromise<gitops$0.Status | null> {
    return $Call.ByID(1385891039);
}

export function SubmitReview($number: number, event: string, body: string, comments: ghapi$0.ReviewComment[] | null): $CancellablePromise<void> {
    return $Call.ByID(3295771057, $number, event, body, comments);
}

export function Switch(branch: string): $CancellablePromise<void> {
    return $Call.ByID(1272999137, branch);
}

export function SwitchNew(branch: string): $CancellablePromise<void> {
    return $Call.ByID(637393581, branch);
}

/**
 * TriggerDispatch fires a workflow_dispatch. inputs is a JSON-ish string map from
 * the frontend; values pass through as strings (GitHub accepts string inputs).
 */
export function TriggerDispatch(workflowFile: string, ref: string, inputs: { [_ in string]?: string } | null): $CancellablePromise<void> {
    return $Call.ByID(3276770057, workflowFile, ref, inputs);
}

export function UnresolveThread(threadID: string): $CancellablePromise<void> {
    return $Call.ByID(3879277182, threadID);
}

export function UnstagePath(path: string): $CancellablePromise<void> {
    return $Call.ByID(3753426035, path);
}

/**
 * UploadAsset takes the file name and its base64-encoded contents (from the
 * frontend file input) and attaches it to the release.
 */
export function UploadAsset(releaseID: number, name: string, dataB64: string): $CancellablePromise<ghapi$0.Asset> {
    return $Call.ByID(996616100, releaseID, name, dataB64);
}
