// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * GitService is the bound service the frontend calls. Every method here
 * delegates to the same internal/ engine the CLI uses.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as ghapi$0 from "../internal/ghapi/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as gitops$0 from "../internal/gitops/models.js";

export function Branches(): $CancellablePromise<gitops$0.Branch[] | null> {
    return $Call.ByID(3913623929);
}

/**
 * GetRepoDir returns the current working directory.
 */
export function GetRepoDir(): $CancellablePromise<string> {
    return $Call.ByID(2807244446);
}

export function Issues(state: string): $CancellablePromise<ghapi$0.Issue[] | null> {
    return $Call.ByID(1294470425, state);
}

export function Log(limit: number): $CancellablePromise<gitops$0.Commit[] | null> {
    return $Call.ByID(2074061505, limit);
}

/**
 * PRs resolves owner/repo from the origin remote of the current dir.
 */
export function PRs(state: string): $CancellablePromise<ghapi$0.PR[] | null> {
    return $Call.ByID(3721264108, state);
}

/**
 * SetRepoDir lets the frontend re-point the service at another repo.
 */
export function SetRepoDir(dir: string): $CancellablePromise<void> {
    return $Call.ByID(1616087450, dir);
}

export function Status(): $CancellablePromise<gitops$0.Status | null> {
    return $Call.ByID(1385891039);
}
