// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Issue is a trimmed issue view.
 */
export interface Issue {
    "Number": number;
    "Title": string;
    "Author": string;
    "State": string;
    "When": string;
}

/**
 * PR is a trimmed pull-request view.
 */
export interface PR {
    "Number": number;
    "Title": string;
    "Author": string;
    "State": string;
    "When": string;
    "Draft": boolean;
}
