// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Asset is a trimmed release-asset view.
 */
export interface Asset {
    "ID": number;
    "Name": string;
    "Size": number;
    "URL": string;
}

/**
 * CheckRun is a trimmed view of one CI check on a commit.
 */
export interface CheckRun {
    "Name": string;

    /**
     * queued, in_progress, completed
     */
    "Status": string;

    /**
     * success, failure, neutral, cancelled, ... (empty until completed)
     */
    "Conclusion": string;
}

/**
 * Issue is a trimmed issue view.
 */
export interface Issue {
    "Number": number;
    "Title": string;
    "Author": string;
    "State": string;
    "When": string;
    "Labels": string[] | null;
}

/**
 * Label is a repo label definition: name, hex color (no leading #), description.
 */
export interface Label {
    "Name": string;
    "Color": string;
    "Description": string;
}

/**
 * PR is a trimmed pull-request view.
 */
export interface PR {
    "Number": number;
    "Title": string;
    "Author": string;
    "State": string;
    "When": string;
    "Draft": boolean;
    "Labels": string[] | null;
}

/**
 * Release is a trimmed GitHub release view.
 */
export interface Release {
    "ID": number;
    "TagName": string;
    "Name": string;
    "Body": string;
    "Draft": boolean;
    "Prerelease": boolean;
    "Immutable": boolean;
    "URL": string;
}

/**
 * Review is a trimmed PR review (a whole-PR verdict).
 */
export interface Review {
    "ID": number;
    "Author": string;

    /**
     * APPROVED, CHANGES_REQUESTED, COMMENTED, DISMISSED, PENDING
     */
    "State": string;
    "Body": string;
}

/**
 * ReviewComment is a pending line comment to attach to a submitted review.
 * Path is the file path; Line is the line number in the file's new version;
 * Body is the comment text.
 */
export interface ReviewComment {
    "Path": string;
    "Line": number;
    "Body": string;
}

/**
 * Reviewer is a requested (not-yet-submitted) reviewer on a PR.
 */
export interface Reviewer {
    "Login": string;
}
