// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CheckRun is a trimmed view of one CI check on a commit.
 */
export interface CheckRun {
    "Name": string;

    /**
     * queued, in_progress, completed
     */
    "Status": string;

    /**
     * success, failure, neutral, cancelled, ... (empty until completed)
     */
    "Conclusion": string;
}

/**
 * Issue is a trimmed issue view.
 */
export interface Issue {
    "Number": number;
    "Title": string;
    "Author": string;
    "State": string;
    "When": string;
}

/**
 * Label is a repo label definition: name, hex color (no leading #), description.
 */
export interface Label {
    "Name": string;
    "Color": string;
    "Description": string;
}

/**
 * PR is a trimmed pull-request view.
 */
export interface PR {
    "Number": number;
    "Title": string;
    "Author": string;
    "State": string;
    "When": string;
    "Draft": boolean;
}

/**
 * Release is a trimmed GitHub release view.
 */
export interface Release {
    "ID": number;
    "TagName": string;
    "Name": string;
    "Body": string;
    "Draft": boolean;
    "Prerelease": boolean;

    /**
     * HTML URL
     */
    "URL": string;
}
